Wishes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorization.urls')),
    path('',include('friends.urls')),
    path('',include('desires.urls')),
]

authorization/urls.py
from django.urls import path
from . import views

app_name='authorization'

urlpatterns = [path('', views.home_view, name ="home"),
			   path('register', views.register_view, name='register'),
			   path('login', views.login_view, name='login'),
			   path('logout', views.logout_view, name='logout'),
			   path('profile/', views.user_profile_view, name="user_profile"),
			   path('profile/<int:ID>', views.profile_view, name="profile")]

authorization/models.py
from django.db import models

# Create your models here.

authorization/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegisterForm(forms.Form):
	email = forms.CharField()
	email.widget = forms.TextInput(attrs={'type': 'email', 'id': 'inputEmail', 'class': 'form-control',
                                       'placeholder': 'Email', 'required': True, 'autofocus': True})
	username = forms.CharField()
	username.widget = forms.TextInput(attrs={'type': 'username', 'id': 'inputUsername',
                                          'class': 'form-control', 'placeholder': 'Логин', 'required': True, 'autofocus': False})
	password = forms.CharField()
	password.widget = forms.PasswordInput(attrs={'type': 'password', 'id': 'inputPassword',
                                              'class': 'form-control', 'placeholder': 'Пароль', 'required': True, 'autofocus': False})
	confirm_password = forms.CharField()
	confirm_password.widget = forms.PasswordInput(attrs={'type': 'password', 'id': 'inputConfirmPassword',
                                                      'class': 'form-control', 'placeholder': 'Подтверждение пароля', 'required': True, 'autofocus': False})

	help_texts = {'email': None, 'username': None, 'password': None}

	def clean(self):
		super(UserRegisterForm, self).clean()
		# Check username busyness
		if User.objects.filter(username=self.cleaned_data['username']).exists():
			raise forms.ValidationError("This username is already taken")

		# Check email busyness
		if User.objects.filter(email=self.cleaned_data['email']).exists():
			raise forms.ValidationError("This email is already taken")

		# Check password matching
		password = self.cleaned_data.get('password')
		confirm_password = self.cleaned_data.get('confirm_password')
		if password and confirm_password and password != confirm_password:
			raise forms.ValidationError('Passwords doesn\'t match')

		# Delete confirm password from form just not to override save() method
		del self.cleaned_data['confirm_password']


class UserLoginForm(forms.Form):
	username = forms.CharField()
	username.widget = forms.TextInput(attrs={'type': 'text', 'id': 'inputUsername',
                                          'class': 'form-control', 'placeholder': 'Логин', 'required': True, 'autofocus': True})

	password = forms.CharField()
	password.widget = forms.PasswordInput(
		attrs={'type': 'password', 'id': 'inputPassword', 'class': 'form-control', 'placeholder': 'Пароль', 'required': True})

	def clean(self):
		super(UserLoginForm, self).clean()
		if not User.objects.filter(username=self.cleaned_data['username']).exists():
			raise forms.ValidationError(
				"Wrong username")

authorization/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from .forms import UserLoginForm
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from desires.models import *
from friends.models import *
from django.db.models import Q


def home_view(request):
	return render(request, "home.html")


def register_view(request):
	if request.user.is_authenticated:
		return redirect('/desires')

	args = {}
	if request.method == 'GET':
		reg_form = UserRegisterForm()
		args['reg_form'] = reg_form
	if request.method == 'POST':
		reg_form = UserRegisterForm(data=request.POST)
		print(reg_form)
		args = {'reg_form': reg_form}
		if reg_form.is_valid():
			new_user = User.objects.create_user(**reg_form.cleaned_data)
			return redirect('/login')
	return render(request, 'register.html', args)


def login_view(request):
	if request.user.is_authenticated:
		return redirect('/desires')
	args = {}
	if request.method == 'GET':
		log_form = UserLoginForm()
		args['log_form'] = log_form
	if request.method == 'POST':
		log_form = UserLoginForm(data=request.POST)
		args['log_form'] = log_form
		if log_form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(request, username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect('/desires')
	return render(request, 'login.html', args)


@login_required
def logout_view(request):
	logout(request)
	return redirect('/login')


@login_required
def user_profile_view(request):
	'''
	Show user profile
	'''
	if request.method == 'GET':
		user = request.user
		desires_list = Desire.objects.filter(user=user)
		args = {'user': user,
                    'desires_list': desires_list,
                    'user_profile': True,
                    'friends_count': Relationship.objects.filter(Q(user1=user) | Q(user2=user)).count(),
                    'desires_count': Desire.objects.filter(user=user).count()}
		return render(request, "profile.html", args)


@login_required
def profile_view(request, ID):
	'''
	Show another person profile
	'''
	if request.method == 'GET':
		user = User.objects.get(pk=ID)
		friends_check = Relationship.objects.filter(
			Q(user1=request.user, user2=user) | Q(user1=user, user2=request.user)).exists()
		desires_list = Desire.objects.filter(user=user)
		args = {'user': user,
                    'desires_list': desires_list,
                    'user_profile': False,
                    'friends_check': friends_check,
                    'friends_count': Relationship.objects.filter(Q(user1=user) | Q(user2=user)).count(),
                    'desires_count': Desire.objects.filter(user=user).count()}
		return render(request, "profile.html", args)

authorization/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/gift.png' %}"/>

</head>
<body>
    <ul>
        <li><a href="{% url 'authorization:login' %}">Login</a></li>
        <li><a href="{% url 'authorization:register' %}">Register</a></li>
    </ul>
    {% block content %}
    {% endblock %}
</body>
</html>

authorization/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/gift.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Login</title>
</head>

<body>
    <div class="container-caption">
        <div class="container text-center">
            {{ error_message }}
            <form class="form-signin" action="login" method="post">
                {% csrf_token %}
                <img class="mb-4" src="{% static 'images/wish.png' %}" alt="" width="72" height="72">

                <h1 class="h3 mb-3 font-weight-normal">Авторизация</h1>
                {{ log_form.username }}
                {{ log_form.password }}
                <button class="btn btn-lg btn-primary btn-block" type="submit">Зайти</button>
                <a href='/register'>Регистрация</a>
                <p class="mt-5 mb-3 text-muted">&copy; Sorokin Gleb 2020</p>
            </form>
        </div>
    </div>
</body>

</html>

authorization/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title%}{{ user.username }}'s profile {% endblock %}

{% block css %}
<style>
.desire {
    position: fixed;
    padding: 10px;
    margin: 0;
}

.gift-image {
    display: inline-block;
    margin-right: 50px;
    float: left;
}

.desire-info {
    display: inline-block;
    float: left;
}

</style>
{% endblock %}

{% block content %}
<div class="profile">
    <div class="image">
        <img src="{% static 'images/user.webp' %}" width="200px" height="200px">

    </div>
    <div class="username-and-status">
        <h3>{{ user.username }}</h3>
        <p>Количесвто друзей: {{ friends_count }}</p>
        <p>Количество желаний: {{ desires_count }}</p>
    </div>
    {% if not user_profile and not friends_check %}
    <a href="/friends/send_request/{{ user.id }}" type="button">Добавить в друзья</a>
    {% endif %}
</div>


<h1>Список желаний пользователя</h1>
<div class="list-group desires">
    {% for desire in desires_list %}
    <div class="list-group-item desire">
        <div class="gift-image">
            {% if desire.image_url %}
            <img src= "{{ desire.image_url }}" width=100px>
            {% else %}
            <img src= "{% static 'images/gift.png' %}">
            {% endif %}
        </div>
        <div class="desire-info">
            <div class="desire-name">
                <b>{{ desire.name }}</b>
            </div>
            <div class="desire-description">
                <i>{{ desire.description }}</i>
            </div>

            <div class="desire-label">
                <span>{{ desire.label.name }}</span>
            </div>
            <div class="desire-creation">
                <span style="color:grey">{{ desire.creation_date }}</span>
            </div>
        </div>
    </div>
    {% empty %}
    {% if not user_profile %}
    </br>
    <h4> {{ user.username }} пока ничего не добавил в список своих желаний </h4>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}

authorization/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/gift.png' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Register</title>
</head>

<body>
    <div class="container-caption">
        <div class="container text-center">
            {{ error_message }}
            <form class="form-signin m-5" action="register" method="post">
                {% csrf_token %}
                <img class="mb-4" src="{% static 'images/wish.png' %}" alt="" width="72" height="72">

                <h1 class="h3 mb-3 font-weight-normal">Регистрация</h1>
                {{ reg_form.email }}
                {{ reg_form.username }}
                {{ reg_form.password }}
                {{ reg_form.confirm_password }}
                <button class="btn btn-lg btn-primary btn-block" type="submit">Зарегистрироваться</button>
                <a href='/login'>Авторизация</a>
                <p class="mt-5 mb-3 text-muted">&copy; Sorokin Gleb 2020</p>
            </form>
        </div>
    </div>
</body>

</html>