Wishes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorization.urls')),
    path('',include('friends.urls')),
    path('',include('desires.urls')),
]

authorization/urls.py
from django.urls import path
from . import views

app_name='authorization'

urlpatterns = [path('', views.home_view, name ="home"),
			   path('register', views.register_view, name='register'),
			   path('login', views.login_view, name='login'),
			   path('logout', views.logout_view, name='logout'),
			   path('profile/', views.user_profile_view, name="user_profile"),
			   path('profile/<int:ID>', views.profile_view, name="profile")]

friends/urls.py
from django.urls import path
from . import views

app_name='friends'

urlpatterns = [path('friends/', views.friends_view, name ="friends"),
               path('explore', views.explore_view, name="explore"),
               path('ajax/explore_users/<str:regexp>', views.explore_users, name="explore_users"),
               path('ajax/explore_users/', views.explore_users_empty, name="explore_users_empty"),   # for empty search request
               path('friends/send_request/<int:ID>', views.send_friend_request, name="send_friend_request"),
               path('friends/accept_request/<int:ID>', views.accept_friend_request, name="accept_friend_request"),
               path('friends/dissolve/<int:ID>',views.dissolve_relationship, name="dissolve"),]

friends/models.py
from django.db import models
from django.contrib.auth.models import User

class Relationship(models.Model):
    # Objects of relationship
    user1 = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user1')  # sender
    user2 = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user2')  # receiver

    # Indicates, that first user or second user accept friendship
    # TODO: think about one field(is_accepted) instead of accept1 and accept
    accept1 = models.BooleanField(default=False)
    accept2 = models.BooleanField(default=False)

    # Relationship beginning date
    relation_start = models.DateTimeField(auto_now_add=True)

friends/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import *
from django.db.models import Q
from django.http.response import HttpResponse


@login_required
def friends_view(request):
    user = request.user
    if request.method == 'GET':
        relationships = Relationship.objects.filter(
            Q(user1=user.id) | Q(user2=user.id))

        # Fill friends list
        friends_list = []
        friend_requests_list = []
        for each in relationships:
            # If GET request user in one field, then add to friends_list user from another field
            if each.user1 == user:
                friends_list.append(each.user2)
            if each.user2 == user:
                # If GET request user is receiver of friend request
                # and he accept request, then add user1 to friends list
                if each.accept2 == True:
                    friends_list.append(each.user1)

                # If GET request user is receiver of friend request
                # and he doesnt accept request, then add user1 to friend requests list
                if each.accept2 == False:
                    friend_requests_list.append(each.user1)

        args = {'friends': friends_list,
                'friend_requests': friend_requests_list}
        return render(request, "friends.html", args)


@login_required
def explore_view(request):
    if request.method == 'GET':
        return render(request, 'explore.html')


"""
TODO:
PROBABLY
From this line will be defined functions needs for js
"""


@login_required
def send_friend_request(request, ID):
    '''Send friend request to user by ID'''
    request_sender = request.user
    if request.method == 'GET':
        # Check that sender send friend request to himself
        if request_sender.id != ID:
            # Check that user with ID exists
            try:
                # Check that user already have some(accepted or not) relationshipwith user where user.id == ID
                rs = Relationship.objects.filter(
                    user2=request_sender, user1=ID)
                if rs.exists():
                    rs = rs.first()
                    if rs.accept2 == True:
                        return render(request, "message.html", {'message':'Вы уже дружите с этим пользователем'})
                    else:
                        return render(request, "message.html", {'message':'Этот пользователь уже отправил вам заявку. Посмотрите во вкладке "Друзья" '})
                else:
                    # Check that sender already send friend request to user with ID
                    if not Relationship.objects.filter(user1=request_sender.id, user2=ID).exists():
                        request_receiver = User.objects.get(pk=ID)
                        new_relationship = Relationship(
                            user1=request_sender, user2=request_receiver, accept1=True)
                        new_relationship.save()
                        return redirect('/friends')
                    else:
                        return render(request, "message.html", {'message':'Вы уже отправили заявку этому пользователю'})
            except User.DoesNotExist:
                return render(request, "message.html", {'message':'Пользователя с таким ID не существует'})
        else:
            return render(request, "message.html", {'message':'Вы не можете отправить заявку самому себе'})


@login_required
def accept_friend_request(request, ID):
    '''Accept friends request from user by ID'''
    user = request.user
    if request.method == 'GET':
        # Check that accepter accept request from himself
        if user.id != ID:
            # Check that friend request was sended
            try:
                relationship_to_accept = Relationship.objects.get(user1=ID)
                # Check that request already accepted
                if relationship_to_accept.accept2 == False:
                    relationship_to_accept.accept2 = True
                    relationship_to_accept.save()

                    return redirect('/friends')
                else:
                    return render(request, "message.html", {'message':'Вы уже друзья'})
            except Relationship.DoesNotExist:
                return render(request, "message.html", {'message':'Такой заявки не существует'})
        else:
            return render(request, "message.html", {'message':'Вы не можете принять заявку от самого себя'})


@login_required
def dissolve_relationship(request, ID):
    '''Dissolve realtionship with user with ID even if receiver user didn\'t accept friend request.
    Relationship dissovler can be user, who send friend request(user1) and also can be user, who receive friend request.
    '''
    dissolve_initiator = request.user
    if request.method == 'GET':
        try:
            # If GET request sender is user1 in the db table, then user2.id = ID,
            # else GET sender is user2 in the db table and user1.id = ID
            relationship_to_dissolve = \
                Relationship.objects.get((Q(user1=ID) | Q(user2=ID)) & (
                    Q(user1=dissolve_initiator) | Q(user2=dissolve_initiator)))
            relationship_to_dissolve.delete()
            return redirect('/friends')
        except Relationship.DoesNotExist:
            return render(request, "message.html", {'message':'Вы не дружите с этим пользователем'})


"""
From this line will be defined functions needs for ajax
"""


@login_required
def explore_users(request, regexp):
    if request.method == 'GET':
        regexp = r'' + regexp
        users_list = User.objects.filter(username__iregex=regexp).exclude(
            pk=request.user.id)  # excluding user, who makes request
        args = {'users': users_list}
        return render(request, 'users.html', args)


@login_required
def explore_users_empty(request):
    if request.method == 'GET':
        args = {'users': User.objects.all().exclude(pk=request.user.id)}
        return render(request, 'users.html', args)

friends/templates/explore.html
{% extends 'base.html' %}
{% block title %} Explore {% endblock %}

{% block css %}
<style>
::selection{
  color: #fff;
  background: #664AFF;
}

.wrapper{
  max-width: 1050px;
  margin: 150px auto;
}

.wrapper .search-input{
  background: #fff;
  width: 100%;
  border-radius: 5px;
  position: relative;
  box-shadow: 0px 1px 5px 3px rgba(0,0,0,0.12);
}

.search-input input{
  height: 55px;
  width: 100%;
  outline: none;
  border: none;
  border-radius: 5px;
  padding: 0 60px 0 20px;
  font-size: 18px;
  box-shadow: 0px 1px 5px rgba(0,0,0,0.1);
}

.search-input.active input{
  border-radius: 5px 5px 0 0;
}

.search-input .autocom-box{
  padding: 0;
  opacity: 0;
  pointer-events: none;
  max-height: 280px;
  overflow-y: auto;
}

.search-input.active .autocom-box{
  padding: 10px 8px;
  opacity: 1;
  pointer-events: auto;
}

.autocom-box li{
  list-style: none;
  padding: 8px 12px;
  display: none;
  width: 100%;
  cursor: default;
  border-radius: 3px;
}

.search-input.active .autocom-box li{
  display: block;
}
.autocom-box li:hover{
  background: #efefef;
}

.search-input .icon{
  position: absolute;
  right: 0px;
  top: 0px;
  height: 55px;
  width: 55px;
  text-align: center;
  line-height: 55px;
  font-size: 20px;
  color: #644bff;
  cursor: pointer;
}
</style>
{% endblock %}

{% block content %}
<div class="wrapper">
  <h1>Найдите новых друзей</h1>
    <div class="search-input">
      <a href="" target="_blank" hidden></a>
      <input type="text" placeholder="Type to search..." id="explore-input">
      <div class="autocom-box">
        <ul id="explored-users">

        </ul>
      </div>
      <div class="icon"><i class="fas fa-search"></i></div>
    </div>
  </div>
{% endblock %}

{% block script%}
<!-- For explore -->
<script src="https://kit.fontawesome.com/a076d05399.js"></script>

<script>
    const searchWrapper = $(".search-input");
    const inputBox = $("input");
    const suggBox = $(".autocom-box");
    const icon = $(".icon");
    let linkTag = $("a");
    
    var explore_input = $("#explore-input")
    explore_input.on("keyup", function (event) {
        searchWrapper.addClass("active");
        /* Send request for get users with matching name  */
        $.ajax({
            type: "GET",
            dataType: "html",
            url: "ajax/explore_users/".concat(explore_input.val()),
            success: function (data) {
                $("#explored-users").html(data)
                console.log(data)
            },
            error: function (info) {
                console.log(info)
            }

        })
    })
</script>
{% endblock %}

friends/templates/friends.html
{% extends 'base.html' %}
{% block title %} Friends{% endblock %}
{% block content %}
<h1 class="ml-3">Заявки в друзья</h1>
<ul class="list-group">
    {% for friend in friend_requests %}
    <li class="list-group-item"> 
        username: <a href="{% url 'authorization:profile' friend.id %}">{{ friend.username }}</a></br>
        <a href="{% url 'friends:accept_friend_request' friend.id %}">Принять</a>
        <a href="{% url 'friends:dissolve' friend.id %}">Отклонить</a>
    </li>
    {% empty %}
    <span class="ml-4">Пока заявок нет</span>
    {% endfor %}
</ul>
<h1 class="ml-3">Ваши друзья</h1>
<ul class="list-group">
    {% for friend in friends %}
    <li class="list-group-item"> 
        username: <a href="{% url 'authorization:profile' friend.id %}">{{ friend.username }}</a></br>
        <a href="{% url 'friends:dissolve' friend.id %}">Удалить</a>
    </li>
    {% empty %}
    <span class="ml-4">Попробуйте найти новых друзей во вкладке "Поиск"</span>
    {% endfor %}
</ul>
{% endblock %}

friends/templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Info Message</title>
</head>
<body>
    <h2> {{ message }} </h2>
</body>
</html>

friends/templates/users.html
{% for user in users %}
    <li><a href="profile/{{ user.id }}">{{ user.username }}</a></li>
{% endfor %}