Wishes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorization.urls')),
    path('',include('friends.urls')),
    path('',include('desires.urls')),
]

desires/urls.py
from django.urls import path
from . import views

app_name='desires'

urlpatterns = [path('desires', views.desires_view, name="desires"),
               path('desires/delete/<ID>', views.desire_delete, name="delete_desire"),
               path('desires/add', views.desire_add, name="add_desire"),
               path('desire/edit/<ID>', views.desire_edit, name="edit_desire")]

desires/models.py
from django.db import models
from django.contrib.auth.models import User

class Label(models.Model):
    name = models.CharField(max_length=20)
    count = models.IntegerField(default=0)

class Desire(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(blank=False, max_length=20)
    description = models.TextField(default='Описания нет')
    url = models.URLField()
    image_url = models.URLField()
    label = models.ForeignKey(Label, on_delete=models.SET_NULL, null=True)
    creation_date = models.DateField(auto_now_add=True)

desires/forms.py
from django import forms

class DesireForm(forms.Form):
	name = forms.CharField()
	description = forms.CharField(required=False)
	# url = forms.URLField(required=False)
	image_url = forms.URLField(required=False)
	label = forms.CharField(required=False)

desires/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import (Desire, Label)
from .forms import *
from django.http.response import HttpResponse


@login_required
def desires_view(request):
    if request.method == 'GET':
        user = request.user
        desires_list = Desire.objects.filter(user=user)
        print(desires_list)
        form = DesireForm()
        args = {'desires_list': desires_list,
                'form': form}
        return render(request, 'desires.html', args)



@login_required
def desire_add(request):
    if request.method == 'POST':
        form = DesireForm(data=request.POST)
        if form.is_valid():
            desire = Desire()
            desire.user = request.user
            desire.name = form.data.get('name')
            if len(form.data.get('description')) > 0:
                desire.description = form.data.get('description')
            desire.image_url = form.data.get('image_url')
            label = Label.objects.create(name=form.data.get('label'))
            desire.label = label
            desire.save()
        args = {'form': form}
        return redirect('/desires')
    else:
        # To avoid add by url
        return redirect('/desires')


@login_required
def desire_delete(request, ID):
    if request.method == 'GET':
        desire = Desire.objects.get(pk=ID)
        if desire.user == request.user:
            desire.delete()
            return redirect('/desires')
        else:
            return HttpResponse("You don't have permission to do this")
    else:
        # To avoid delete by url
        return redirect('/desires')

@login_required
def desire_edit(request, ID):
    if request.method == 'POST':
        form = DesireForm(data=request.POST)
        if form.is_valid():
            desire = Desire.objects.get(pk=ID)
            desire.name = form.data.get('name')
            if form.data.get('description') != '':
                desire.description = form.data.get('description')
            desire.image_url = form.data.get('image_url')
            label = Label.objects.create(name=form.data.get('label'))
            desire.label = label
            desire.save()
        args = {'form': form}
        return redirect('/desires')
    else:
        # To avoid add by url
        return redirect('/desires')

desires/templates/desires.html
{% extends 'base.html' %}
{% load static %}
{% block title%} Desires {% endblock %}

{% block css %}

{% endblock%}

{% block content %}
<div class="desires-container">
    <div class="row m-4">
        {% for desire in desires_list %}
        <div class="card m-1" style="width: 18rem;">
            {% if desire.image_url %}
            <img class="card-img-top" src=" {{ desire.image_url }}" alt="Card image cap">
            {% else %}
            <img class="card-img-top" src="{% static 'images/wish.png' %}" alt="Card image cap">
            {% endif %}

            <div class="card-body">
                <h5 class="card-title">{{ desire.name }} <span class="badge badge-secondary"
                        style="font-size: 0.8rem">{{ desire.label.name }}</span></h5>
                <p class="card-text">{{ desire.description }}</p>
                <a href="{{ desire.url }}">{{ desire.url }}</a>
                <p>{{ desire.creation_date }}</p>
                <a href="{% url 'desires:delete_desire' desire.id %}" class="btn btn-danger">Удалить</a>
                <a href="" class="btn btn-secondary a-edit" value="{% url 'desires:edit_desire' desire.id %}"
                    data-toggle="modal" data-target="#modal-form-edit">Изменить</a>
            </div>
        </div>
        {% empty %}
        <h3>Добавьте свои желания сюда!</h3>
        {% endfor %}
    </div>
</div>

<div class="edit-desire">
    <div id="modal-form-edit" class="modal m-5" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id='edit-form' method="POST" action="desires/edit">
                    <div class="modal-header">
                        <h3>Вы хотите что-то изменить?</h3>
                    </div>
                    <div class="modal-body">
                        <div class="form">
                            {% csrf_token %}
                            <p>
                                <label for="id_name">Имя: </label>
                                {{ form.name }}
                            </p>
                            <p>
                                <label for="id_description">Описание: </label>
                                {{ form.description }}
                            </p>

                            <p>
                                <label for="id_image_url">Ссылка на каринку: </label>
                                {{ form.image_url }}
                            </p>

                            <p>
                                <label for="id_image_url">Тэг: </label>
                                {{ form.label }}
                            </p>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="add-desire">
    <button class="btn btn-primary ml-4" data-toggle="modal" data-target="#modal-form-delete">Добавить</button>
    <div id="modal-form-delete" class="modal m-5" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form method="POST" action="desires/add">
                    <div class="modal-header">
                        <h3>Что вы хотите?</h3>

                    </div>
                    <div class="modal-body">
                        <div class="form">
                            {% csrf_token %}
                            <p>
                                <label for="id_name">Имя: </label>
                                {{ form.name }}
                            </p>
                            <p>
                                <label for="id_description">Описание: </label>
                                {{ form.description }}
                            </p>

                            <p>
                                <label for="id_image_url">Ссылка на каринку: </label>
                                {{ form.image_url }}
                            </p>

                            <p>
                                <label for="id_image_url">Тэг: </label>
                                {{ form.label }}
                            </p>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    $('.a-edit').on('click', function () {
        console.log('TEST', $(this).attr('value'))
        $('#edit-form').attr('action', $(this).attr('value'))
    })
</script>
{% endblock %}